baseURL = 'https://belablotski.github.io/'
languageCode = 'en-us'
title = 'Aliaksei Belablotski'
theme = 'ananke'
# theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
# resourceDir = './resources'
# sectionPagesMenu = 'main'
enableRobotsTXT = true

[services.googleAnalytics]
id = 'G-2D0K5REC2D'

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
# site_logo = "images/gohugo-default-sample-hero-image.jpg"
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 3
[customCSS]
  href = "/css/custom.css"


[params.ananke.social.share]
networks = [
  "email",
  "facebook",
  "twitter",
  "bluesky",
  "linkedin"
]

[params.ananke.social.follow]
networks = [
  "twitter",
  "linkedin"
]

[params.ananke.social.twitter]
username = "belablotski"

[params.ananke.social.linkedin]
username = "belablotski"

[markup]
  [markup.tableOfContents]
    # See https://gohugo.io/methods/page/tableofcontents/
    startLevel = 2
    endLevel = 3
    ordered = true

# [services.disqus]
# shortname = 'YOURSHORTNAME'
